/*
 * unicode.h — Unicode code point classification for BPE pre-tokenizers.
 *
 * The flag bits and the UTF-8 decoding rules mirror llama.cpp's
 * `unicode_cpt_flags` / `unicode_cpts_from_utf8` exactly, because the
 * pre-tokenizer splits (and therefore the token ids) must match llama.cpp
 * bit-for-bit. The tables live in src/util/unicode_data.c, generated by
 * scripts/gen_unicode_tables.py from llama.cpp's unicode-data.cpp.
 */
#ifndef OXIDIZE_UNICODE_H
#define OXIDIZE_UNICODE_H

#include <stdbool.h>
#include <stddef.h>
#include <stdint.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Category flags (same bit values as llama.cpp unicode_cpt_flags). */
#define OC_UCPT_UNDEFINED   0x0001u
#define OC_UCPT_NUMBER      0x0002u  /* \p{N} */
#define OC_UCPT_LETTER      0x0004u  /* \p{L} */
#define OC_UCPT_SEPARATOR   0x0008u  /* \p{Z} */
#define OC_UCPT_ACCENT_MARK 0x0010u  /* \p{M} */
#define OC_UCPT_PUNCTUATION 0x0020u  /* \p{P} */
#define OC_UCPT_SYMBOL      0x0040u  /* \p{S} */
#define OC_UCPT_CONTROL     0x0080u  /* \p{C} */
#define OC_UCPT_WHITESPACE  0x0100u  /* \s    */

/* Replacement code point emitted for undecodable UTF-8 bytes. */
#define OC_UCPT_REPLACEMENT 0xFFFDu

/* Generated tables (src/util/unicode_data.c). */
extern const size_t   oc_unicode_n_ranges;
extern const uint32_t oc_unicode_range_start[];
extern const uint8_t  oc_unicode_range_flags[];
extern const size_t   oc_unicode_n_whitespace;
extern const uint32_t oc_unicode_whitespace[];
extern const size_t   oc_unicode_n_lower;
extern const uint32_t oc_unicode_lower_from[];
extern const uint32_t oc_unicode_lower_to[];

/* Category flags | OC_UCPT_WHITESPACE for `cp`. Code points >= 0x110000
 * report OC_UCPT_UNDEFINED. Never returns 0. */
uint16_t oc_unicode_cpt_flags(uint32_t cp);

/* Simple (1:1) lowercase mapping; returns `cp` when it has none. */
uint32_t oc_unicode_tolower(uint32_t cp);

/* Decode UTF-8 into code points with llama.cpp's rules: structurally valid
 * 1-4 byte sequences decode as-is (no overlong/surrogate checks); every
 * byte that does not start a complete sequence becomes one
 * OC_UCPT_REPLACEMENT. `out` must hold at least `len` entries. Returns the
 * number of code points written. */
size_t oc_unicode_cpts_from_utf8(const char *s, size_t len, uint32_t *out);

/* Encode `cp` as UTF-8 into `out` (up to 4 bytes). Code points above
 * 0x10FFFF are encoded as U+FFFD. Returns the byte count. */
size_t oc_unicode_cpt_to_utf8(uint32_t cp, char out[4]);

#ifdef __cplusplus
}
#endif

#endif /* OXIDIZE_UNICODE_H */
