[package]
name = "llamas-core"
edition.workspace = true
license.workspace = true
version.workspace = true
build = "build.rs"

[features]
default = []
cuda = ["dep:cublas-sys", "dep:cust"]

[dependencies]
anyhow.workspace = true
cublas-sys = { version = "0.1", optional = true }
cust = { version = "0.3", optional = true }
memmap2 = "0.9"
rayon = "1"
serde.workspace = true
thiserror.workspace = true

[dev-dependencies]
criterion = "0.5"

[[bench]]
name = "criterion"
harness = false
