/* Quantization kernel tests.
 *
 * Four layers, in increasing strength:
 *   1. golden vectors  — dequant a known block, compare to values generated by
 *      tools/gen_golden.py from the block-layout spec (tests/golden.h). Catches
 *      a decoder that is self-consistently wrong.
 *   2. one-hot dots    — oc_dot_row(row, e_i) must equal dequant(row)[i] for
 *      every i. A random x averages a single bad lane away; e_i cannot.
 *   3. ISA differential — layers 1+2 re-run under oc_force_isa() at EVERY ISA
 *      level this CPU supports, each compared elementwise against scalar. A
 *      mis-wired dispatch table diverges numerically instead of crashing, so
 *      this is the acceptance test for the table.
 *   4. binding check   — the dispatch table must actually have rebound. A table
 *      that left every type on the scalar kernel would sail through layer 3.
 */
#include <math.h>
#include <string.h>

#include "../src/quant.h"
#include "../src/tensor.h"
#include "golden.h"
#include "tests.h"

#define COLS 512 /* 16 QK blocks / 2 K blocks */

static unsigned rnd_state = 1;
static uint8_t rnd_byte(void) {
  rnd_state = rnd_state * 1103515245u + 12345u;
  return (uint8_t)(rnd_state >> 16);
}
static float rnd_f(void) { return (float)(rnd_byte() - 128) * (1.0f / 128.0f); }

static void put_f16(uint8_t* p, float v) {
  uint16_t h = oc_f32_to_f16(v);
  p[0] = (uint8_t)(h & 0xff);
  p[1] = (uint8_t)(h >> 8);
}

/* A row of `COLS` values of type t: random payload bytes, with the f16 scale
 * fields overwritten with sane finite values (random f16 bit patterns are
 * inf/NaN often enough that the comparisons would be testing NaN handling
 * rather than the kernels). */
static void make_row(uint32_t t, uint8_t* row, unsigned seed) {
  rnd_state = seed;
  size_t bytes = oc_row_bytes(t, COLS);
  CHECK(bytes > 0);
  for (size_t i = 0; i < bytes; ++i) row[i] = rnd_byte();
  switch (t) {
    case OC_F32:
      for (size_t i = 0; i < COLS; ++i) {
        float v = rnd_f();
        memcpy(row + 4 * i, &v, 4);
      }
      break;
    case OC_F16:
      for (size_t i = 0; i < COLS; ++i) put_f16(row + 2 * i, rnd_f());
      break;
    case OC_BF16:
      /* bf16 = high 16 bits of a finite f32; random bits would be inf/NaN. */
      for (size_t i = 0; i < COLS; ++i) {
        float v = rnd_f();
        uint32_t bits;
        memcpy(&bits, &v, 4);
        uint16_t h = (uint16_t)(bits >> 16);
        row[2 * i] = (uint8_t)(h & 0xff);
        row[2 * i + 1] = (uint8_t)(h >> 8);
      }
      break;
    case OC_Q4_0:
    case OC_Q8_0:
    case OC_Q5_0:
      /* d f16 at block start. */
      for (size_t b = 0; b < COLS / OC_QK; ++b)
        put_f16(row + b * oc_row_bytes(t, OC_QK), 0.01f + 0.002f * (float)b);
      break;
    case OC_Q4_1:
    case OC_Q5_1:
      /* d, m both f16 at block start. */
      for (size_t b = 0; b < COLS / OC_QK; ++b) {
        uint8_t* blk = row + b * oc_row_bytes(t, OC_QK);
        put_f16(blk, 0.01f + 0.002f * (float)b);
        put_f16(blk + 2, -0.05f);
      }
      break;
    case OC_Q4_K:
    case OC_Q5_K:
      for (size_t b = 0; b < COLS / OC_QK_K; ++b) {
        uint8_t* blk = row + b * oc_row_bytes(t, OC_QK_K);
        put_f16(blk, 0.021f + 0.003f * (float)b);
        put_f16(blk + 2, 0.011f);
      }
      break;
    case OC_Q2_K:
      /* d f16 at [80], dmin f16 at [82]. */
      for (size_t b = 0; b < COLS / OC_QK_K; ++b) {
        uint8_t* blk = row + b * OC_BLK_Q2_K;
        put_f16(blk + 80, 0.015f + 0.002f * (float)b);
        put_f16(blk + 82, 0.004f);
      }
      break;
    case OC_Q3_K:
      /* d f16 at [108]. */
      for (size_t b = 0; b < COLS / OC_QK_K; ++b)
        put_f16(row + b * OC_BLK_Q3_K + 108, 0.0068f);
      break;
    case OC_IQ4_XS:
      /* d f16 at block start. Kept small: IQ4_XS reconstruction levels reach
       * ±127, so a hot scale makes the synthetic dot cancel catastrophically
       * and the GEMM-vs-matvec FP-order differential exceeds 1e-4 for reasons
       * unrelated to the (golden-verified) unpack. */
      for (size_t b = 0; b < COLS / OC_QK_K; ++b)
        put_f16(row + b * OC_BLK_IQ4_XS, 0.006f + 0.001f * (float)b);
      break;
    case OC_IQ2_XXS:
    case OC_IQ2_XS:
    case OC_IQ2_S:
    case OC_IQ3_XXS:
    case OC_IQ3_S:
    case OC_IQ1_S:
      /* f16 d at block start. Kept small so the matmul-vs-matvec FP-order
       * differential stays under 1e-4 despite the ±sign grid cancellation. */
      for (size_t b = 0; b < COLS / OC_QK_K; ++b)
        put_f16(row + b * oc_row_bytes(t, OC_QK_K), 0.006f + 0.001f * (float)b);
      break;
    case OC_IQ1_M:
      /* No d field: the f16 scale is packed into the top nibble of each of the
       * 4 u16 block scales at offset 48. Set those nibbles so d is sane finite;
       * the low 12 bits (per-32 sub-scales) stay random. */
      for (size_t b = 0; b < COLS / OC_QK_K; ++b) {
        uint8_t* blk = row + b * OC_BLK_IQ1_M;
        uint16_t H = oc_f32_to_f16(0.02f + 0.004f * (float)b);
        for (int k = 0; k < 4; ++k)
          blk[48 + 2 * k + 1] = (uint8_t)((blk[48 + 2 * k + 1] & 0x0f) |
                                          (((H >> (4 * k)) & 0xf) << 4));
      }
      break;
    case OC_Q6_K:
      for (size_t b = 0; b < COLS / OC_QK_K; ++b)
        put_f16(row + b * OC_BLK_Q6_K + 208, 0.0068f);
      break;
    case OC_AL5_XS:
      for (size_t b = 0; b < COLS / OC_QK; ++b)
        put_f16(row + b * OC_BLK_AL5_XS, 0.05f + 0.001f * (float)b);
      break;
    default:
      CHECK(0);
  }
}

/* out[0..COLS-1] = dot with e_i; out[COLS] = dot with a full random vector. */
static void probe(uint32_t t, const uint8_t* row, const float* x, float* out) {
  float e[COLS];
  memset(e, 0, sizeof e);
  for (size_t i = 0; i < COLS; ++i) {
    e[i] = 1.0f;
    out[i] = oc_dot_row(t, row, e, COLS);
    e[i] = 0.0f;
  }
  out[COLS] = oc_dot_row(t, row, x, COLS);
}

static void close_to(const char* what, uint32_t t, size_t i, float got, float want,
                     float rel) {
  if (fabsf(got - want) <= rel * (1.0f + fabsf(want))) return;
  fprintf(stderr, "FAIL %s: type %u idx %zu: got %.9g want %.9g\n", what, t, i, (double)got,
          (double)want);
  exit(1);
}

static const uint32_t TYPES[] = {
    OC_F32,  OC_F16,  OC_BF16, OC_Q4_0,   OC_Q4_1,   OC_Q5_0, OC_Q5_1, OC_Q8_0,
    OC_Q2_K, OC_Q3_K, OC_Q4_K, OC_Q5_K,   OC_Q6_K,   OC_IQ4_XS,
    OC_IQ2_XXS, OC_IQ2_XS, OC_IQ2_S, OC_IQ3_XXS, OC_IQ3_S, OC_IQ1_S, OC_IQ1_M,
    OC_AL5_XS};
#define N_TYPES (sizeof TYPES / sizeof TYPES[0])

void test_quant_golden(void) {
  float out[OC_QK_K];

  /* f16: hand-picked bit patterns (1.0, -2.0, max normal, min subnormal, -0). */
  const uint8_t f16row[12] = {0x00, 0x3c, 0x00, 0xc0, 0xff, 0x7b,
                              0x01, 0x00, 0x00, 0x80, 0x55, 0x35};
  const float f16exp[6] = {1.0f, -2.0f, 65504.0f, 5.9604645e-8f, -0.0f, 0.33325195f};
  CHECK(oc_dequant_row(OC_F16, f16row, out, 6) == 0);
  for (size_t i = 0; i < 6; ++i) CHECK(out[i] == f16exp[i]);
  CHECK(oc_f32_to_f16(1.0f) == 0x3c00 && oc_f32_to_f16(-2.0f) == 0xc000);

  /* f32: identity. */
  const float f32row[4] = {1.5f, -0.25f, 0.0f, 1e30f};
  CHECK(oc_dequant_row(OC_F32, (const uint8_t*)f32row, out, 4) == 0);
  for (size_t i = 0; i < 4; ++i) CHECK(out[i] == f32row[i]);

#define GOLD(TY, NAME, N)                                                  \
  do {                                                                     \
    CHECK(oc_row_bytes(TY, N) == sizeof GOLD_##NAME);                      \
    CHECK(oc_dequant_row(TY, GOLD_##NAME, out, N) == 0);                   \
    for (size_t i = 0; i < (N); ++i)                                       \
      close_to("golden " #NAME, TY, i, out[i], GOLD_##NAME##_EXP[i], 1e-5f); \
  } while (0)
  GOLD(OC_Q4_0, Q4_0, OC_QK);
  GOLD(OC_Q4_1, Q4_1, OC_QK);
  GOLD(OC_Q5_0, Q5_0, OC_QK);
  GOLD(OC_Q5_1, Q5_1, OC_QK);
  GOLD(OC_Q8_0, Q8_0, OC_QK);
  GOLD(OC_Q2_K, Q2_K, OC_QK_K);
  GOLD(OC_Q3_K, Q3_K, OC_QK_K);
  GOLD(OC_Q4_K, Q4_K, OC_QK_K);
  GOLD(OC_Q5_K, Q5_K, OC_QK_K);
  GOLD(OC_Q6_K, Q6_K, OC_QK_K);
  GOLD(OC_IQ4_XS, IQ4_XS, OC_QK_K);
  GOLD(OC_IQ2_XXS, IQ2_XXS, OC_QK_K);
  GOLD(OC_IQ2_XS, IQ2_XS, OC_QK_K);
  GOLD(OC_IQ2_S, IQ2_S, OC_QK_K);
  GOLD(OC_IQ3_XXS, IQ3_XXS, OC_QK_K);
  GOLD(OC_IQ3_S, IQ3_S, OC_QK_K);
  GOLD(OC_IQ1_S, IQ1_S, OC_QK_K);
  GOLD(OC_IQ1_M, IQ1_M, OC_QK_K);
  GOLD(OC_BF16, BF16, 8);
  GOLD(OC_AL5_XS, AL5_XS, OC_QK);
#undef GOLD

  /* Unsupported types must fail loudly, not return a wrong number. */
  CHECK(oc_row_bytes(9999, 256) == 0);
  CHECK(oc_dequant_row(9999, GOLD_Q4_0, out, 32) == -1);
  /* Ragged rows have no valid byte length. */
  CHECK(oc_row_bytes(OC_Q4_K, 128) == 0);
  CHECK(oc_row_bytes(OC_Q4_0, 31) == 0);
  CHECK(oc_row_bytes(OC_Q2_K, 128) == 0);
  CHECK(oc_row_bytes(OC_IQ4_XS, 255) == 0);
  CHECK(oc_row_bytes(OC_Q5_0, 33) == 0);
  CHECK(oc_row_bytes(OC_IQ2_XXS, 128) == 0);
  CHECK(oc_row_bytes(OC_IQ1_S, 255) == 0);
  CHECK(oc_row_bytes(OC_IQ1_M, 128) == 0);
  /* Exact ggml block sizes (a wrong grid-quant block size is silent garbage). */
  CHECK(oc_row_bytes(OC_IQ2_XXS, OC_QK_K) == OC_BLK_IQ2_XXS);
  CHECK(oc_row_bytes(OC_IQ2_XS, OC_QK_K) == OC_BLK_IQ2_XS);
  CHECK(oc_row_bytes(OC_IQ2_S, OC_QK_K) == OC_BLK_IQ2_S);
  CHECK(oc_row_bytes(OC_IQ3_XXS, OC_QK_K) == OC_BLK_IQ3_XXS);
  CHECK(oc_row_bytes(OC_IQ3_S, OC_QK_K) == OC_BLK_IQ3_S);
  CHECK(oc_row_bytes(OC_IQ1_S, OC_QK_K) == OC_BLK_IQ1_S);
  CHECK(oc_row_bytes(OC_IQ1_M, OC_QK_K) == OC_BLK_IQ1_M);

  printf("ok quant golden vectors (f32 f16 bf16 q4_0 q4_1 q5_0 q5_1 q8_0 "
         "q2_k q3_k q4_k q5_k q6_k iq4_xs iq2_xxs iq2_xs iq2_s iq3_xxs iq3_s "
         "iq1_s iq1_m al5_xs)\n");
}

static const char* ISA_NAME[] = {"scalar", "avx2", "avx512", "neon"};

/* The non-scalar ISA tiers that can exist in THIS build (the arch is fixed at
 * compile time, so an x86 binary never sees NEON and vice-versa). The
 * differential forces each in turn and compares elementwise to scalar. */
#if defined(__aarch64__)
static const OcIsa SIMD_LEVELS[] = {OC_ISA_NEON};
#else
static const OcIsa SIMD_LEVELS[] = {OC_ISA_AVX2, OC_ISA_AVX512};
#endif
#define N_SIMD (sizeof SIMD_LEVELS / sizeof SIMD_LEVELS[0])

/* Which types are expected to bind a kernel of their own at each ISA level.
 * A new kernel must be added here, or the binding check below fails: that is
 * the point — it is the tripwire for a kernel that got written but never
 * wired into the dispatch table. */
static int has_kernel(uint32_t t, int lvl) {
#if defined(__aarch64__)
  /* NEON fused dots: the K-quants, BF16, and (unlike x86) Q4_0/Q8_0. */
  if (lvl < OC_ISA_NEON) return 0;
  return t == OC_Q4_0 || t == OC_Q8_0 || t == OC_Q4_K || t == OC_Q5_K ||
         t == OC_Q6_K || t == OC_BF16;
#else
  /* AVX2 fused dots exist for all K-quants, IQ4_XS, BF16 and AL5_XS; the AVX-512
   * TU only adds wider Q5_K/Q6_K/Q4_K/AL5_XS variants, so the *set* of non-scalar
   * types is the same at both levels (the rest stay on the AVX2 kernels). */
  if (lvl < OC_ISA_AVX2) return 0;
  return t == OC_Q4_K || t == OC_Q5_K || t == OC_Q6_K || t == OC_Q2_K ||
         t == OC_Q3_K || t == OC_IQ4_XS || t == OC_BF16 || t == OC_AL5_XS;
#endif
}

/* Same, for the vectorized whole-row dequant kernels oc_matmul depends on. */
static int has_deq_kernel(uint32_t t, int lvl) {
#if defined(__aarch64__)
  if (lvl >= OC_ISA_NEON)
    return t == OC_Q4_K || t == OC_Q5_K || t == OC_Q6_K;
  return 0;
#else
  if (lvl >= OC_ISA_AVX2)
    return t == OC_Q4_K || t == OC_Q5_K || t == OC_Q6_K || t == OC_AL5_XS;
  return 0;
#endif
}

void test_quant_dot(void) {
  static uint8_t row[COLS * 4];
  static float ref[COLS + 1], got[COLS + 1], deq[COLS];
  float x[COLS];
  char what[64];

  OcIsa best = oc_isa_available();
  CHECK(best == OC_ISA_SCALAR || best == OC_ISA_AVX2 ||
        best == OC_ISA_AVX512 || best == OC_ISA_NEON);

  for (size_t k = 0; k < N_TYPES; ++k) {
    uint32_t t = TYPES[k];
    make_row(t, row, 0xC0FFEEu + (unsigned)k * 7919u);
    rnd_state = 99u + (unsigned)k;
    for (size_t i = 0; i < COLS; ++i) x[i] = rnd_f();

    /* Reference: the scalar kernels, against the independent dequant path. */
    oc_force_isa(OC_ISA_SCALAR);
    CHECK(oc_isa_active() == OC_ISA_SCALAR);
    const void* scalar_impl = oc_dot_impl(t);
    CHECK(scalar_impl != NULL);
    CHECK(oc_dequant_row(t, row, deq, COLS) == 0);
    probe(t, row, x, ref);
    for (size_t i = 0; i < COLS; ++i)
      close_to("scalar dot vs dequant", t, i, ref[i], deq[i], 1e-5f);
    /* full-vector dot: different accumulation order, so only ~1e-4 relative */
    close_to("scalar dot vs dequant+dot_f32", t, COLS, ref[COLS],
             oc_dot_f32(deq, x, COLS), 1e-4f);

    /* Every SIMD tier this build/CPU actually has, against that reference. */
    for (size_t li = 0; li < N_SIMD; ++li) {
      int lvl = (int)SIMD_LEVELS[li];
      if (lvl > (int)best) continue;
      oc_force_isa((OcIsa)lvl);
      CHECK(oc_isa_active() == (OcIsa)lvl);
      /* the table must have rebound exactly where a kernel exists */
      CHECK((oc_dot_impl(t) != scalar_impl) == has_kernel(t, lvl));
      CHECK((oc_dequant_impl(t) != NULL) == has_deq_kernel(t, lvl));

      /* The SIMD whole-row dequant feeds oc_matmul, which is the only consumer
       * that never re-checks it against a dot. Compare it to scalar directly. */
      static float deq_isa[COLS];
      CHECK(oc_dequant_row(t, row, deq_isa, COLS) == 0);
      for (size_t i = 0; i < COLS; ++i) {
        snprintf(what, sizeof what, "%s dequant vs scalar dequant", ISA_NAME[lvl]);
        close_to(what, t, i, deq_isa[i], deq[i], 1e-6f);
      }
      probe(t, row, x, got);
      for (size_t i = 0; i < COLS; ++i) {
        snprintf(what, sizeof what, "%s dot vs dequant", ISA_NAME[lvl]);
        close_to(what, t, i, got[i], deq[i], 1e-5f);
        snprintf(what, sizeof what, "%s vs scalar (one-hot)", ISA_NAME[lvl]);
        close_to(what, t, i, got[i], ref[i], 1e-6f);
      }
      snprintf(what, sizeof what, "%s vs scalar (random x)", ISA_NAME[lvl]);
      close_to(what, t, COLS, got[COLS], ref[COLS], 1e-4f);
    }
  }
  oc_force_isa(OC_ISA_AUTO);
  printf("ok quant dot: dequant-agreement + differential over %zu types x "
         "{scalar..%s} (active=%s)\n",
         N_TYPES, ISA_NAME[best], oc_isa_active_name());
}

/* oc_matmul vs oc_matvec: the GEMM must agree with the (already dequant-verified)
 * matvec for every type, every ISA, and token counts that land on and off the
 * kernel's 8/16/32-wide tiles. A GEMM that dropped a k block or mixed up the
 * k-major panel layout produces plausible-looking numbers, so this compares the
 * whole [n_tokens][rows] result, not a norm. */
#define MM_ROWS 70 /* not a multiple of the 64-row tile */

void test_matmul(void) {
  static uint8_t W[MM_ROWS * COLS * 4];
  static float X[32 * COLS], Y[32 * MM_ROWS], ref[MM_ROWS];
  const size_t toks[] = {1, 2, 3, 8, 16, 17, 32};
  char what[96];

  OcCtx* c = oc_ctx_new();
  CHECK(c != NULL);
  OcIsa best = oc_isa_available();
  oc_force_isa(OC_ISA_SCALAR);
  const void* gemm_scalar = oc_gemm_impl();
  CHECK(gemm_scalar != NULL);

  rnd_state = 7u;
  for (size_t i = 0; i < 32 * COLS; ++i) X[i] = rnd_f();

  for (size_t k = 0; k < N_TYPES; ++k) {
    uint32_t t = TYPES[k];
    size_t rb = oc_row_bytes(t, COLS);
    for (size_t r = 0; r < MM_ROWS; ++r)
      make_row(t, W + r * rb, 0xBEEFu + (unsigned)(k * MM_ROWS + r) * 31u);

    for (size_t li = 0; li <= N_SIMD; ++li) {
      int lvl = li == 0 ? (int)OC_ISA_SCALAR : (int)SIMD_LEVELS[li - 1];
      if (lvl > (int)best) continue;
      oc_force_isa((OcIsa)lvl);
      /* a SIMD gemm kernel that never got wired into the table would still pass
       * the numeric differential below — it would just be scalar. Every SIMD
       * tier binds a non-scalar gemm; only scalar keeps gemm_scalar. */
      CHECK((oc_gemm_impl() != gemm_scalar) == (lvl != OC_ISA_SCALAR));
      for (size_t ti = 0; ti < sizeof toks / sizeof toks[0]; ++ti) {
        size_t n = toks[ti];
        oc_matmul(c, Y, t, W, MM_ROWS, COLS, X, n);
        for (size_t i = 0; i < n; ++i) {
          oc_matvec(c, ref, t, W, MM_ROWS, COLS, X + i * COLS);
          for (size_t r = 0; r < MM_ROWS; ++r) {
            snprintf(what, sizeof what, "%s matmul n=%zu tok=%zu vs matvec",
                     ISA_NAME[lvl], n, i);
            close_to(what, t, r, Y[i * MM_ROWS + r], ref[r], 1e-4f);
          }
        }
      }
    }
  }
  oc_force_isa(OC_ISA_AUTO);
  oc_ctx_free(c);
  printf("ok matmul: == matvec over %zu types x {scalar..%s} x {1,2,3,8,16,17,32} "
         "tokens\n", N_TYPES, ISA_NAME[best]);
}

/* int8-activation path: compiled always, bound only on an AVX512-VNNI CPU. */
void test_quant_q8_act(void) {
  oc_force_isa(OC_ISA_AUTO);
  if (!oc_q8_dot_supported(OC_Q4_K)) {
    printf("skip q8 activation path: this CPU has no AVX512-VNNI (isa=%s)\n",
           oc_isa_active_name());
    return;
  }
  static uint8_t row[COLS * 4];
  static int8_t q[COLS], q_ref[COLS];
  float x[COLS], d[COLS / 256], d_ref[COLS / 256];
  int32_t bs[COLS / 16], bs_ref[COLS / 16];

  rnd_state = 4242;
  for (size_t i = 0; i < COLS; ++i) x[i] = rnd_f();
  oc_q8_quantize(x, COLS, q, d, bs);
  oc_force_isa(OC_ISA_SCALAR);
  oc_q8_quantize(x, COLS, q_ref, d_ref, bs_ref);
  oc_force_isa(OC_ISA_AUTO);
  CHECK(memcmp(q, q_ref, sizeof q) == 0);
  for (size_t i = 0; i < COLS / 256; ++i) CHECK(d[i] == d_ref[i]);
  for (size_t i = 0; i < COLS / 16; ++i) CHECK(bs[i] == bs_ref[i]);

  const OcQ8Act act = {q, d, bs};
  static float w[COLS], xq[COLS];
  for (size_t i = 0; i < COLS; ++i) xq[i] = (float)q[i] * d[i / 256];
  const uint32_t types[3] = {OC_Q4_K, OC_Q5_K, OC_Q6_K};
  for (int k = 0; k < 3; ++k) {
    CHECK(oc_q8_dot_supported(types[k]));
    make_row(types[k], row, 0x5EEDu + (unsigned)k);
    float ref = oc_dot_row(types[k], row, x, COLS);
    float got = oc_dot_row_q8(types[k], row, &act, COLS);
    /* 8-bit activations: ~0.4% of the row norm is the honest bound here */
    close_to("q8 dot vs f32 dot", types[k], 0, got, ref, 2e-2f);
    /* The decisive one: against the SAME int8-rounded activations the kernel
     * sees. Activation loss cancels out, so anything but float-rounding here is
     * a kernel bug -- e.g. Q6_K's -32 offset folded through the wrong bsum lane,
     * which the f32 comparison above hides inside its 2e-2 slack. */
    oc_dequant_row(types[k], row, w, COLS);
    double exact = 0, norm = 0;
    for (size_t i = 0; i < COLS; ++i) {
      exact += (double)w[i] * xq[i];
      norm += fabs((double)w[i] * xq[i]);
    }
    CHECK(fabs(got - exact) <= 1e-5 * norm);
  }
  CHECK(!oc_q8_dot_supported(OC_Q4_0)); /* no VNNI kernel: must say so */
  printf("ok q8 activation path (quantize scalar==simd, dot within 2e-2)\n");
}
