#!/usr/bin/env python3
"""Generate oxidize-c/src/util/unicode_data.c (Unicode category tables).

The BPE pre-tokenizers (src/format/pretokenize.c) must classify code points
exactly like llama.cpp does, otherwise token ids diverge. llama.cpp ships its
own snapshot of the Unicode Character Database in `src/unicode-data.cpp`
(generated by its scripts/gen-unicode-data.py from UnicodeData.txt). This
script transcribes that snapshot into a compact C table so the two engines
agree bit-for-bit, independent of the host Python's unicodedata version.

Emitted tables:
  * oc_unicode_range_start[] / oc_unicode_range_flags[] — sorted range starts
    and the category flags (\\p{N} \\p{L} \\p{Z} \\p{M} \\p{P} \\p{S} \\p{C},
    undefined) valid until the next start. The final sentinel is 0x110000.
  * oc_unicode_whitespace[]  — the `\\s` code points (sorted).
  * oc_unicode_lower_from[] / oc_unicode_lower_to[] — simple lowercase map.

Usage:
  python3 scripts/gen_unicode_tables.py path/to/llama.cpp/src/unicode-data.cpp
  (writes src/util/unicode_data.c; pass -o to override)

A `--python` mode rebuilds the category ranges from Python's unicodedata
instead (for when no llama.cpp checkout is at hand). It is NOT guaranteed to
match llama.cpp's snapshot for code points assigned in newer Unicode
versions, so the committed table is generated from unicode-data.cpp.
"""
from __future__ import annotations

import argparse
import re
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
DEFAULT_OUT = ROOT / "src" / "util" / "unicode_data.c"
MAX_CP = 0x110000

# Must match include/oxidize/unicode.h (and llama.cpp unicode_cpt_flags).
UNDEFINED, NUMBER, LETTER, SEPARATOR, ACCENT_MARK = 0x01, 0x02, 0x04, 0x08, 0x10
PUNCTUATION, SYMBOL, CONTROL = 0x20, 0x40, 0x80


def section(text: str, name: str) -> str:
    m = re.search(re.escape(name) + r"\s*=\s*\{(.*?)\n\};", text, re.S)
    if not m:
        sys.exit(f"gen_unicode_tables: section {name} not found")
    return m.group(1)


def from_llama(path: Path):
    text = path.read_text()
    pairs = [(int(a, 16), int(b, 16)) for a, b in
             re.findall(r"\{0x([0-9A-Fa-f]+),\s*0x([0-9A-Fa-f]+)\}",
                        section(text, "unicode_ranges_flags"))]
    ws = sorted(int(x, 16) for x in
                re.findall(r"0x([0-9A-Fa-f]+)", section(text, "unicode_set_whitespace")))
    lower = [(int(a, 16), int(b, 16)) for a, b in
             re.findall(r"\{0x([0-9A-Fa-f]+),\s*0x([0-9A-Fa-f]+)\}",
                        section(text, "unicode_map_lowercase"))]
    return pairs, ws, lower


def from_python():
    import unicodedata
    cat_map = {"N": NUMBER, "L": LETTER, "Z": SEPARATOR, "M": ACCENT_MARK,
               "P": PUNCTUATION, "S": SYMBOL, "C": CONTROL}
    pairs = []
    prev = None
    for cp in range(MAX_CP):
        cat = unicodedata.category(chr(cp))
        f = UNDEFINED if cat == "Cn" else cat_map[cat[0]]
        if f != prev:
            pairs.append((cp, f))
            prev = f
    pairs.append((MAX_CP, 0))
    # str.isspace() also accepts the 0x1C..0x1F separators; llama.cpp's
    # `\s` set does not.
    ws = sorted(cp for cp in range(MAX_CP)
                if chr(cp).isspace() and not 0x1C <= cp <= 0x1F)
    lower = []
    for cp in range(MAX_CP):
        lo = chr(cp).lower()
        if len(lo) == 1 and ord(lo) != cp:
            lower.append((cp, ord(lo)))
    return pairs, ws, lower


def emit(pairs, ws, lower, source: str) -> str:
    assert pairs[0][0] == 0 and pairs[-1][0] == MAX_CP, "bad range sentinels"
    for a, b in zip(pairs, pairs[1:]):
        assert a[0] < b[0], "ranges must be strictly ascending"
    for start, flags in pairs[:-1]:
        # Every assigned range carries a category bit (Cn -> UNDEFINED), so a
        # zero flags value only ever means "outside the text".
        assert flags != 0 and flags <= 0xFF, f"unexpected flags {flags:#x} at {start:#x}"
    assert lower == sorted(lower), "lowercase map must be sorted"

    out = []
    w = out.append
    w("/* unicode_data.c — GENERATED by scripts/gen_unicode_tables.py. DO NOT EDIT.")
    w(" *")
    w(f" * Source: {source}")
    w(" * Category ranges, whitespace set, and simple lowercase map used by the")
    w(" * BPE pre-tokenizers (see include/oxidize/unicode.h). */")
    w("")
    w('#include "oxidize/unicode.h"')
    w("")
    w("#include <stddef.h>")
    w("#include <stdint.h>")
    w("")
    w(f"const size_t oc_unicode_n_ranges = {len(pairs)};")
    w("")
    w("const uint32_t oc_unicode_range_start[] = {")
    for i in range(0, len(pairs), 8):
        w("    " + ", ".join(f"0x{p[0]:06X}" for p in pairs[i:i + 8]) + ",")
    w("};")
    w("")
    w("const uint8_t oc_unicode_range_flags[] = {")
    for i in range(0, len(pairs), 12):
        w("    " + ", ".join(f"0x{p[1]:02X}" for p in pairs[i:i + 12]) + ",")
    w("};")
    w("")
    w(f"const size_t oc_unicode_n_whitespace = {len(ws)};")
    w("")
    w("const uint32_t oc_unicode_whitespace[] = {")
    for i in range(0, len(ws), 8):
        w("    " + ", ".join(f"0x{c:06X}" for c in ws[i:i + 8]) + ",")
    w("};")
    w("")
    w(f"const size_t oc_unicode_n_lower = {len(lower)};")
    w("")
    w("const uint32_t oc_unicode_lower_from[] = {")
    for i in range(0, len(lower), 8):
        w("    " + ", ".join(f"0x{p[0]:06X}" for p in lower[i:i + 8]) + ",")
    w("};")
    w("")
    w("const uint32_t oc_unicode_lower_to[] = {")
    for i in range(0, len(lower), 8):
        w("    " + ", ".join(f"0x{p[1]:06X}" for p in lower[i:i + 8]) + ",")
    w("};")
    w("")
    return "\n".join(out)


def main() -> None:
    ap = argparse.ArgumentParser(description=__doc__,
                                 formatter_class=argparse.RawDescriptionHelpFormatter)
    ap.add_argument("unicode_data_cpp", nargs="?", type=Path,
                    help="llama.cpp src/unicode-data.cpp")
    ap.add_argument("--python", action="store_true",
                    help="derive tables from Python unicodedata instead")
    ap.add_argument("-o", "--output", type=Path, default=DEFAULT_OUT)
    args = ap.parse_args()
    if args.python:
        import unicodedata
        pairs, ws, lower = from_python()
        source = f"Python unicodedata {unicodedata.unidata_version}"
    else:
        if not args.unicode_data_cpp:
            ap.error("unicode_data_cpp path required (or --python)")
        pairs, ws, lower = from_llama(args.unicode_data_cpp)
        source = "llama.cpp src/unicode-data.cpp (llama.cpp-k2 fork snapshot)"
    args.output.write_text(emit(pairs, ws, lower, source))
    print(f"wrote {args.output}: {len(pairs)} ranges, {len(ws)} whitespace, "
          f"{len(lower)} lowercase pairs")


if __name__ == "__main__":
    main()
