[package]
name = "oxidize-server"
edition.workspace = true
license.workspace = true
version.workspace = true

[lib]
name = "oxidize_server"
path = "src/lib.rs"

[[bin]]
name = "oxidize-server"
path = "src/main.rs"

[dependencies]
axum.workspace = true
clap.workspace = true
oxidize-core = { path = "../oxidize-core" }
serde.workspace = true
serde_json = "1"
tokio.workspace = true
tracing.workspace = true
futures-util = "0.3"
rand = "0.8"
tracing-subscriber = "0.3"
subtle = "2.6"
prometheus = "0.14.0"
uuid = { version = "1.23.1", features = ["v4", "serde"] }
chrono = "0.4.44"

[dev-dependencies]
tower = { version = "0.5", features = ["util"] }
