[package]
name = "oxidize-convert"
edition.workspace = true
license.workspace = true
version.workspace = true

[[bin]]
name = "oxidize-convert"
path = "src/main.rs"

[dependencies]
anyhow.workspace = true
clap.workspace = true
oxidize-core = { version = "0.1.0", path = "../oxidize-core" }
oxidize-prune = { version = "0.1.0", path = "../oxidize-prune" }
