[package]
name = "oxidize-convert"
edition.workspace = true
license.workspace = true
version.workspace = true

[[bin]]
name = "oxidize-convert"
path = "src/main.rs"

[dependencies]
anyhow.workspace = true
clap.workspace = true
memmap2 = "0.9"
safetensors = "0.4"
serde_json = "1"
oxidize-core = { path = "../oxidize-core" }
