#include "oxidize/kv_cache_vk.hpp"

#include <vulkan/vulkan.h>

#include <cmath>
#include <cstring>
#include <map>
#include <stdexcept>
#include <utility>

// SPIR-V blobs generated by glslc -mfmt=c (see CMake shader step).
static const uint32_t kHelixLogitsSpv[] =
#include "helix_logits.spv.h"
    ;
static const uint32_t kSoftmaxSpv[] =
#include "softmax.spv.h"
    ;
static const uint32_t kHelixPageAccSpv[] =
#include "helix_page_acc.spv.h"
    ;
static const uint32_t kRotorLogitsSpv[] =
#include "rotor_logits.spv.h"
    ;
static const uint32_t kRotorPageAccSpv[] =
#include "rotor_page_acc.spv.h"
    ;

namespace oxidize {
namespace {

void vk_check(VkResult r, const char* what) {
  if (r != VK_SUCCESS) {
    throw std::runtime_error(std::string("VulkanKv: ") + what + " failed (" +
                             std::to_string(static_cast<int>(r)) + ")");
  }
}

struct Buffer {
  VkBuffer buf = VK_NULL_HANDLE;
  VkDeviceMemory mem = VK_NULL_HANDLE;
  void* map = nullptr;
  VkDeviceSize size = 0;
};

struct Pipeline {
  VkDescriptorSetLayout dsl = VK_NULL_HANDLE;
  VkPipelineLayout layout = VK_NULL_HANDLE;
  VkPipeline pipe = VK_NULL_HANDLE;
};

constexpr float kPi = 3.14159265358979323846f;

}  // namespace

struct VulkanKv::Impl {
  VkInstance instance = VK_NULL_HANDLE;
  VkPhysicalDevice phys = VK_NULL_HANDLE;
  VkDevice device = VK_NULL_HANDLE;
  VkQueue queue = VK_NULL_HANDLE;
  uint32_t queue_family = 0;
  VkCommandPool cmd_pool = VK_NULL_HANDLE;
  VkCommandBuffer cmd = VK_NULL_HANDLE;
  VkFence fence = VK_NULL_HANDLE;
  uint32_t host_mem_type = 0;
  std::string device_name;

  Pipeline helix_logits;   // 11 SSBOs
  Pipeline softmax;        // 1 SSBO
  Pipeline helix_acc;      // 5 SSBOs
  Pipeline rotor_logits;   // 4 SSBOs
  Pipeline rotor_acc;      // 5 SSBOs
  VkDescriptorPool pool = VK_NULL_HANDLE;

  struct HelixSlot {
    size_t tokens = 0;
    size_t pages = 0;
    size_t pairs = 0;
    size_t head_dim = 0;
    Buffer key_codes, active, mu, minlog, steplog;
    Buffer positions, page_of, page_off;
    Buffer value_codes, value_scales;
    Buffer query;  // freq | qmag | qphi, pairs floats each
    Buffer logits, page_out;
    VkDescriptorSet ds_logits = VK_NULL_HANDLE;
    VkDescriptorSet ds_softmax = VK_NULL_HANDLE;
    VkDescriptorSet ds_acc = VK_NULL_HANDLE;
  };
  struct RotorSlot {
    size_t tokens = 0;
    size_t pages = 0;
    size_t head_dim = 0;
    size_t blocks = 0;
    Buffer key_codes, key_scales, value_codes, value_scales;
    Buffer page_off, rq, logits, page_out;
    VkDescriptorSet ds_logits = VK_NULL_HANDLE;
    VkDescriptorSet ds_softmax = VK_NULL_HANDLE;
    VkDescriptorSet ds_acc = VK_NULL_HANDLE;
  };
  std::map<std::pair<size_t, size_t>, HelixSlot> helix_slots;
  std::map<std::pair<size_t, size_t>, RotorSlot> rotor_slots;

  ~Impl() {
    if (device == VK_NULL_HANDLE) {
      if (instance != VK_NULL_HANDLE) vkDestroyInstance(instance, nullptr);
      return;
    }
    vkDeviceWaitIdle(device);
    for (auto* slots : {&helix_slots}) {
      for (auto& [key, s] : *slots) destroy_helix_slot(s);
    }
    for (auto& [key, s] : rotor_slots) destroy_rotor_slot(s);
    if (pool) vkDestroyDescriptorPool(device, pool, nullptr);
    for (Pipeline* p :
         {&helix_logits, &softmax, &helix_acc, &rotor_logits, &rotor_acc}) {
      if (p->pipe) vkDestroyPipeline(device, p->pipe, nullptr);
      if (p->layout) vkDestroyPipelineLayout(device, p->layout, nullptr);
      if (p->dsl) vkDestroyDescriptorSetLayout(device, p->dsl, nullptr);
    }
    if (fence) vkDestroyFence(device, fence, nullptr);
    if (cmd_pool) vkDestroyCommandPool(device, cmd_pool, nullptr);
    vkDestroyDevice(device, nullptr);
    vkDestroyInstance(instance, nullptr);
  }

  Buffer create_buffer(VkDeviceSize size) {
    Buffer b;
    b.size = size;
    VkBufferCreateInfo bi{};
    bi.sType = VK_STRUCTURE_TYPE_BUFFER_CREATE_INFO;
    bi.size = size;
    bi.usage = VK_BUFFER_USAGE_STORAGE_BUFFER_BIT;
    bi.sharingMode = VK_SHARING_MODE_EXCLUSIVE;
    vk_check(vkCreateBuffer(device, &bi, nullptr, &b.buf), "create buffer");
    VkMemoryRequirements req;
    vkGetBufferMemoryRequirements(device, b.buf, &req);
    VkMemoryAllocateInfo ai{};
    ai.sType = VK_STRUCTURE_TYPE_MEMORY_ALLOCATE_INFO;
    ai.allocationSize = req.size;
    ai.memoryTypeIndex = host_mem_type;
    vk_check(vkAllocateMemory(device, &ai, nullptr, &b.mem), "alloc memory");
    vk_check(vkBindBufferMemory(device, b.buf, b.mem, 0), "bind memory");
    vk_check(vkMapMemory(device, b.mem, 0, VK_WHOLE_SIZE, 0, &b.map),
             "map memory");
    return b;
  }

  void destroy_buffer(Buffer& b) {
    if (b.buf) vkDestroyBuffer(device, b.buf, nullptr);
    if (b.mem) vkFreeMemory(device, b.mem, nullptr);
    b = Buffer{};
  }

  void destroy_helix_slot(HelixSlot& s) {
    for (Buffer* b : {&s.key_codes, &s.active, &s.mu, &s.minlog, &s.steplog,
                      &s.positions, &s.page_of, &s.page_off, &s.value_codes,
                      &s.value_scales, &s.query, &s.logits, &s.page_out}) {
      destroy_buffer(*b);
    }
  }

  void destroy_rotor_slot(RotorSlot& s) {
    for (Buffer* b : {&s.key_codes, &s.key_scales, &s.value_codes,
                      &s.value_scales, &s.page_off, &s.rq, &s.logits,
                      &s.page_out}) {
      destroy_buffer(*b);
    }
  }

  Pipeline create_pipeline(const uint32_t* spv, size_t spv_bytes,
                           uint32_t bindings, uint32_t push_bytes) {
    Pipeline p;
    std::vector<VkDescriptorSetLayoutBinding> binds(bindings);
    for (uint32_t i = 0; i < bindings; ++i) {
      binds[i].binding = i;
      binds[i].descriptorType = VK_DESCRIPTOR_TYPE_STORAGE_BUFFER;
      binds[i].descriptorCount = 1;
      binds[i].stageFlags = VK_SHADER_STAGE_COMPUTE_BIT;
    }
    VkDescriptorSetLayoutCreateInfo dsli{};
    dsli.sType = VK_STRUCTURE_TYPE_DESCRIPTOR_SET_LAYOUT_CREATE_INFO;
    dsli.bindingCount = bindings;
    dsli.pBindings = binds.data();
    vk_check(vkCreateDescriptorSetLayout(device, &dsli, nullptr, &p.dsl),
             "descriptor set layout");
    VkPushConstantRange range{VK_SHADER_STAGE_COMPUTE_BIT, 0, push_bytes};
    VkPipelineLayoutCreateInfo pli{};
    pli.sType = VK_STRUCTURE_TYPE_PIPELINE_LAYOUT_CREATE_INFO;
    pli.setLayoutCount = 1;
    pli.pSetLayouts = &p.dsl;
    pli.pushConstantRangeCount = 1;
    pli.pPushConstantRanges = &range;
    vk_check(vkCreatePipelineLayout(device, &pli, nullptr, &p.layout),
             "pipeline layout");
    VkShaderModuleCreateInfo smi{};
    smi.sType = VK_STRUCTURE_TYPE_SHADER_MODULE_CREATE_INFO;
    smi.codeSize = spv_bytes;
    smi.pCode = spv;
    VkShaderModule module;
    vk_check(vkCreateShaderModule(device, &smi, nullptr, &module),
             "shader module");
    VkComputePipelineCreateInfo cpi{};
    cpi.sType = VK_STRUCTURE_TYPE_COMPUTE_PIPELINE_CREATE_INFO;
    cpi.stage.sType = VK_STRUCTURE_TYPE_PIPELINE_SHADER_STAGE_CREATE_INFO;
    cpi.stage.stage = VK_SHADER_STAGE_COMPUTE_BIT;
    cpi.stage.module = module;
    cpi.stage.pName = "main";
    cpi.layout = p.layout;
    vk_check(vkCreateComputePipelines(device, VK_NULL_HANDLE, 1, &cpi, nullptr,
                                      &p.pipe),
             "compute pipeline");
    vkDestroyShaderModule(device, module, nullptr);
    return p;
  }

  VkDescriptorSet alloc_set(VkDescriptorSetLayout dsl) {
    VkDescriptorSetAllocateInfo ai{};
    ai.sType = VK_STRUCTURE_TYPE_DESCRIPTOR_SET_ALLOCATE_INFO;
    ai.descriptorPool = pool;
    ai.descriptorSetCount = 1;
    ai.pSetLayouts = &dsl;
    VkDescriptorSet set;
    vk_check(vkAllocateDescriptorSets(device, &ai, &set), "alloc descriptors");
    return set;
  }

  void write_set(VkDescriptorSet set, const std::vector<VkBuffer>& buffers) {
    std::vector<VkDescriptorBufferInfo> infos(buffers.size());
    std::vector<VkWriteDescriptorSet> writes(buffers.size());
    for (size_t i = 0; i < buffers.size(); ++i) {
      infos[i] = {buffers[i], 0, VK_WHOLE_SIZE};
      writes[i] = {};
      writes[i].sType = VK_STRUCTURE_TYPE_WRITE_DESCRIPTOR_SET;
      writes[i].dstSet = set;
      writes[i].dstBinding = static_cast<uint32_t>(i);
      writes[i].descriptorCount = 1;
      writes[i].descriptorType = VK_DESCRIPTOR_TYPE_STORAGE_BUFFER;
      writes[i].pBufferInfo = &infos[i];
    }
    vkUpdateDescriptorSets(device, static_cast<uint32_t>(writes.size()),
                           writes.data(), 0, nullptr);
  }

  void barrier_compute() {
    VkMemoryBarrier mb{};
    mb.sType = VK_STRUCTURE_TYPE_MEMORY_BARRIER;
    mb.srcAccessMask = VK_ACCESS_SHADER_WRITE_BIT;
    mb.dstAccessMask = VK_ACCESS_SHADER_READ_BIT | VK_ACCESS_SHADER_WRITE_BIT;
    vkCmdPipelineBarrier(cmd, VK_PIPELINE_STAGE_COMPUTE_SHADER_BIT,
                         VK_PIPELINE_STAGE_COMPUTE_SHADER_BIT, 0, 1, &mb, 0,
                         nullptr, 0, nullptr);
  }

  void submit_and_wait() {
    vk_check(vkEndCommandBuffer(cmd), "end command buffer");
    VkSubmitInfo si{};
    si.sType = VK_STRUCTURE_TYPE_SUBMIT_INFO;
    si.commandBufferCount = 1;
    si.pCommandBuffers = &cmd;
    vk_check(vkResetFences(device, 1, &fence), "reset fence");
    vk_check(vkQueueSubmit(queue, 1, &si, fence), "queue submit");
    vk_check(vkWaitForFences(device, 1, &fence, VK_TRUE, UINT64_MAX),
             "wait fence");
  }

  void begin_cmd() {
    vk_check(vkResetCommandBuffer(cmd, 0), "reset command buffer");
    VkCommandBufferBeginInfo bi{};
    bi.sType = VK_STRUCTURE_TYPE_COMMAND_BUFFER_BEGIN_INFO;
    bi.flags = VK_COMMAND_BUFFER_USAGE_ONE_TIME_SUBMIT_BIT;
    vk_check(vkBeginCommandBuffer(cmd, &bi), "begin command buffer");
  }

  void dispatch(const Pipeline& p, VkDescriptorSet ds, const void* push,
                uint32_t push_bytes, uint32_t groups) {
    vkCmdBindPipeline(cmd, VK_PIPELINE_BIND_POINT_COMPUTE, p.pipe);
    vkCmdBindDescriptorSets(cmd, VK_PIPELINE_BIND_POINT_COMPUTE, p.layout, 0, 1,
                            &ds, 0, nullptr);
    vkCmdPushConstants(cmd, p.layout, VK_SHADER_STAGE_COMPUTE_BIT, 0,
                       push_bytes, push);
    vkCmdDispatch(cmd, groups, 1, 1);
  }

  struct HelixPush {
    uint32_t n_tokens, pairs, query_position;
  };
  struct SoftmaxPush {
    uint32_t n;
    float scale;
  };
  struct RotorPush {
    uint32_t n_tokens, head_dim, blocks;
  };
  struct RotorAccPush {
    uint32_t head_dim, blocks;
  };

  void fill_helix_query(HelixSlot& s, const std::vector<float>& query,
                        float rope_theta) {
    auto* q = static_cast<float*>(s.query.map);
    for (size_t p = 0; p < s.pairs; ++p) {
      const float x = query[2 * p];
      const float y = query[2 * p + 1];
      q[p] = std::pow(rope_theta, -2.0f * static_cast<float>(p) /
                                      static_cast<float>(s.head_dim));
      q[s.pairs + p] = std::sqrt(x * x + y * y);
      q[2 * s.pairs + p] = std::atan2(y, x);
    }
  }

  void record_helix_logits(HelixSlot& s, size_t query_position) {
    const HelixPush pc{static_cast<uint32_t>(s.tokens),
                       static_cast<uint32_t>(s.pairs),
                       static_cast<uint32_t>(query_position)};
    dispatch(helix_logits, s.ds_logits, &pc, sizeof(pc),
             static_cast<uint32_t>((s.tokens + 63) / 64));
  }

  void record_softmax(VkDescriptorSet ds, size_t n, size_t head_dim) {
    const SoftmaxPush pc{static_cast<uint32_t>(n),
                         1.0f / std::sqrt(static_cast<float>(head_dim))};
    dispatch(softmax, ds, &pc, sizeof(pc), 1);
  }

  void record_helix_acc(HelixSlot& s) {
    const uint32_t pc = static_cast<uint32_t>(s.head_dim);
    dispatch(helix_acc, s.ds_acc, &pc, sizeof(pc),
             static_cast<uint32_t>(s.pages));
  }

  void record_rotor_logits(RotorSlot& s) {
    const RotorPush pc{static_cast<uint32_t>(s.tokens),
                       static_cast<uint32_t>(s.head_dim),
                       static_cast<uint32_t>(s.blocks)};
    dispatch(rotor_logits, s.ds_logits, &pc, sizeof(pc),
             static_cast<uint32_t>((s.tokens + 63) / 64));
  }

  void record_rotor_acc(RotorSlot& s) {
    const RotorAccPush pc{static_cast<uint32_t>(s.head_dim),
                          static_cast<uint32_t>(s.blocks)};
    dispatch(rotor_acc, s.ds_acc, &pc, sizeof(pc),
             static_cast<uint32_t>(s.pages));
  }

  static void reduce_pages(const Buffer& page_out, size_t pages,
                           size_t head_dim, std::vector<float>& out) {
    out.assign(head_dim, 0.0f);
    const float* src = static_cast<const float*>(page_out.map);
    for (size_t p = 0; p < pages; ++p) {
      for (size_t i = 0; i < head_dim; ++i) {
        out[i] += src[p * head_dim + i];
      }
    }
  }
};

bool VulkanKv::available() {
  try {
    VulkanKv probe;
    return true;
  } catch (const std::exception&) {
    return false;
  }
}

VulkanKv::VulkanKv() : impl_(std::make_unique<Impl>()) {
  Impl& v = *impl_;
  VkApplicationInfo app{};
  app.sType = VK_STRUCTURE_TYPE_APPLICATION_INFO;
  app.pApplicationName = "oxidize-kv";
  app.apiVersion = VK_API_VERSION_1_1;
  VkInstanceCreateInfo ici{};
  ici.sType = VK_STRUCTURE_TYPE_INSTANCE_CREATE_INFO;
  ici.pApplicationInfo = &app;
  vk_check(vkCreateInstance(&ici, nullptr, &v.instance), "create instance");

  uint32_t count = 0;
  vkEnumeratePhysicalDevices(v.instance, &count, nullptr);
  if (count == 0) {
    throw std::runtime_error("VulkanKv: no Vulkan devices");
  }
  std::vector<VkPhysicalDevice> devices(count);
  vkEnumeratePhysicalDevices(v.instance, &count, devices.data());
  // Prefer discrete > integrated > anything with a compute queue.
  int best_score = -1;
  for (VkPhysicalDevice d : devices) {
    uint32_t qcount = 0;
    vkGetPhysicalDeviceQueueFamilyProperties(d, &qcount, nullptr);
    std::vector<VkQueueFamilyProperties> families(qcount);
    vkGetPhysicalDeviceQueueFamilyProperties(d, &qcount, families.data());
    for (uint32_t f = 0; f < qcount; ++f) {
      if (!(families[f].queueFlags & VK_QUEUE_COMPUTE_BIT)) {
        continue;
      }
      VkPhysicalDeviceProperties props;
      vkGetPhysicalDeviceProperties(d, &props);
      int score = props.deviceType == VK_PHYSICAL_DEVICE_TYPE_DISCRETE_GPU ? 2
                  : props.deviceType == VK_PHYSICAL_DEVICE_TYPE_INTEGRATED_GPU
                      ? 1
                      : 0;
      if (score > best_score) {
        best_score = score;
        v.phys = d;
        v.queue_family = f;
        v.device_name = props.deviceName;
      }
      break;
    }
  }
  if (v.phys == VK_NULL_HANDLE) {
    throw std::runtime_error("VulkanKv: no compute queue found");
  }

  const float prio = 1.0f;
  VkDeviceQueueCreateInfo qci{};
  qci.sType = VK_STRUCTURE_TYPE_DEVICE_QUEUE_CREATE_INFO;
  qci.queueFamilyIndex = v.queue_family;
  qci.queueCount = 1;
  qci.pQueuePriorities = &prio;
  VkDeviceCreateInfo dci{};
  dci.sType = VK_STRUCTURE_TYPE_DEVICE_CREATE_INFO;
  dci.queueCreateInfoCount = 1;
  dci.pQueueCreateInfos = &qci;
  vk_check(vkCreateDevice(v.phys, &dci, nullptr, &v.device), "create device");
  vkGetDeviceQueue(v.device, v.queue_family, 0, &v.queue);

  VkPhysicalDeviceMemoryProperties mem;
  vkGetPhysicalDeviceMemoryProperties(v.phys, &mem);
  // Prefer host-cached memory: the CPU reads results back from these buffers,
  // and write-combined (uncached) mappings make those reads ~100x slower.
  bool found = false;
  const VkMemoryPropertyFlags base = VK_MEMORY_PROPERTY_HOST_VISIBLE_BIT |
                                     VK_MEMORY_PROPERTY_HOST_COHERENT_BIT;
  for (VkMemoryPropertyFlags want :
       {base | VK_MEMORY_PROPERTY_HOST_CACHED_BIT, base}) {
    for (uint32_t i = 0; i < mem.memoryTypeCount && !found; ++i) {
      if ((mem.memoryTypes[i].propertyFlags & want) == want) {
        v.host_mem_type = i;
        found = true;
      }
    }
    if (found) {
      break;
    }
  }
  if (!found) {
    throw std::runtime_error("VulkanKv: no host-visible memory type");
  }
  // ponytail: host-visible memory everywhere; add device-local + staging when
  // a discrete GPU shows PCIe-bound decode.

  VkCommandPoolCreateInfo cpi{};
  cpi.sType = VK_STRUCTURE_TYPE_COMMAND_POOL_CREATE_INFO;
  cpi.flags = VK_COMMAND_POOL_CREATE_RESET_COMMAND_BUFFER_BIT;
  cpi.queueFamilyIndex = v.queue_family;
  vk_check(vkCreateCommandPool(v.device, &cpi, nullptr, &v.cmd_pool),
           "command pool");
  VkCommandBufferAllocateInfo cbi{};
  cbi.sType = VK_STRUCTURE_TYPE_COMMAND_BUFFER_ALLOCATE_INFO;
  cbi.commandPool = v.cmd_pool;
  cbi.level = VK_COMMAND_BUFFER_LEVEL_PRIMARY;
  cbi.commandBufferCount = 1;
  vk_check(vkAllocateCommandBuffers(v.device, &cbi, &v.cmd), "command buffer");
  VkFenceCreateInfo fci{};
  fci.sType = VK_STRUCTURE_TYPE_FENCE_CREATE_INFO;
  vk_check(vkCreateFence(v.device, &fci, nullptr, &v.fence), "fence");

  v.helix_logits = v.create_pipeline(kHelixLogitsSpv, sizeof(kHelixLogitsSpv),
                                     9, 3 * sizeof(uint32_t));
  v.softmax = v.create_pipeline(kSoftmaxSpv, sizeof(kSoftmaxSpv), 1,
                                sizeof(uint32_t) + sizeof(float));
  v.helix_acc = v.create_pipeline(kHelixPageAccSpv, sizeof(kHelixPageAccSpv),
                                  5, sizeof(uint32_t));
  v.rotor_logits = v.create_pipeline(kRotorLogitsSpv, sizeof(kRotorLogitsSpv),
                                     4, 3 * sizeof(uint32_t));
  v.rotor_acc = v.create_pipeline(kRotorPageAccSpv, sizeof(kRotorPageAccSpv),
                                  5, 2 * sizeof(uint32_t));

  VkDescriptorPoolSize pool_size{VK_DESCRIPTOR_TYPE_STORAGE_BUFFER, 1024};
  VkDescriptorPoolCreateInfo dpi{};
  dpi.sType = VK_STRUCTURE_TYPE_DESCRIPTOR_POOL_CREATE_INFO;
  dpi.maxSets = 256;
  dpi.poolSizeCount = 1;
  dpi.pPoolSizes = &pool_size;
  vk_check(vkCreateDescriptorPool(v.device, &dpi, nullptr, &v.pool),
           "descriptor pool");
}

VulkanKv::~VulkanKv() = default;
VulkanKv::VulkanKv(VulkanKv&&) noexcept = default;
VulkanKv& VulkanKv::operator=(VulkanKv&&) noexcept = default;

std::string VulkanKv::device_name() const { return impl_->device_name; }

void VulkanKv::upload(const HelixCache& cache, const HelixCacheConfig& config) {
  Impl& v = *impl_;
  const size_t pairs = config.head_dim / 2;
  if (pairs % 8 != 0) {
    throw std::invalid_argument("VulkanKv: head_dim must be a multiple of 16");
  }
  for (auto& [key, slot] : v.helix_slots) {
    v.destroy_helix_slot(slot);
  }
  v.helix_slots.clear();

  // Group pages by (layer, head), preserving order.
  std::map<std::pair<size_t, size_t>, std::vector<HelixColdPageView>> grouped;
  for (size_t i = 0; i < cache.page_count(); ++i) {
    HelixColdPageView view;
    if (cache.cold_page_view(i, &view)) {
      grouped[{view.layer, view.kv_head}].push_back(view);
    }
  }
  const size_t groups8 = config.head_dim / 8;
  for (auto& [key, views] : grouped) {
    Impl::HelixSlot slot;
    slot.pairs = pairs;
    slot.head_dim = config.head_dim;
    slot.pages = views.size();
    for (const auto& view : views) {
      slot.tokens += view.tokens;
    }
    const size_t n = slot.tokens;
    slot.key_codes = v.create_buffer(n * pairs);
    slot.active = v.create_buffer(n * pairs / 8);
    slot.mu = v.create_buffer(slot.pages * pairs * sizeof(float));
    slot.minlog = v.create_buffer(slot.pages * pairs * sizeof(float));
    slot.steplog = v.create_buffer(slot.pages * pairs * sizeof(float));
    slot.positions = v.create_buffer(n * sizeof(uint32_t));
    slot.page_of = v.create_buffer(n * sizeof(uint32_t));
    slot.page_off = v.create_buffer((slot.pages + 1) * sizeof(uint32_t));
    slot.value_codes = v.create_buffer(n * config.head_dim * 3 / 8);
    slot.value_scales = v.create_buffer(slot.pages * groups8 * sizeof(float));
    slot.query = v.create_buffer(3 * pairs * sizeof(float));
    slot.logits = v.create_buffer(n * sizeof(float));
    slot.page_out = v.create_buffer(slot.pages * config.head_dim * sizeof(float));

    size_t tok = 0;
    auto* positions = static_cast<uint32_t*>(slot.positions.map);
    auto* page_of = static_cast<uint32_t*>(slot.page_of.map);
    auto* page_off = static_cast<uint32_t*>(slot.page_off.map);
    for (size_t p = 0; p < views.size(); ++p) {
      const auto& view = views[p];
      page_off[p] = static_cast<uint32_t>(tok);
      std::memcpy(static_cast<uint8_t*>(slot.key_codes.map) + tok * pairs,
                  view.key_codes, view.tokens * pairs);
      std::memcpy(static_cast<uint8_t*>(slot.active.map) + tok * pairs / 8,
                  view.active_mask, view.tokens * pairs / 8);
      std::memcpy(static_cast<float*>(slot.mu.map) + p * pairs, view.mu_phi,
                  pairs * sizeof(float));
      std::memcpy(static_cast<float*>(slot.minlog.map) + p * pairs,
                  view.log_rho_min, pairs * sizeof(float));
      std::memcpy(static_cast<float*>(slot.steplog.map) + p * pairs,
                  view.log_rho_step, pairs * sizeof(float));
      std::memcpy(static_cast<uint8_t*>(slot.value_codes.map) +
                      tok * config.head_dim * 3 / 8,
                  view.value_codes, view.tokens * config.head_dim * 3 / 8);
      std::memcpy(static_cast<float*>(slot.value_scales.map) + p * groups8,
                  view.value_scales, groups8 * sizeof(float));
      for (size_t t = 0; t < view.tokens; ++t) {
        positions[tok + t] = static_cast<uint32_t>(view.positions[t]);
        page_of[tok + t] = static_cast<uint32_t>(p);
      }
      tok += view.tokens;
    }
    page_off[slot.pages] = static_cast<uint32_t>(tok);

    slot.ds_logits = v.alloc_set(v.helix_logits.dsl);
    v.write_set(slot.ds_logits,
                {slot.key_codes.buf, slot.active.buf, slot.mu.buf,
                 slot.minlog.buf, slot.steplog.buf, slot.query.buf,
                 slot.positions.buf, slot.page_of.buf, slot.logits.buf});
    slot.ds_softmax = v.alloc_set(v.softmax.dsl);
    v.write_set(slot.ds_softmax, {slot.logits.buf});
    slot.ds_acc = v.alloc_set(v.helix_acc.dsl);
    v.write_set(slot.ds_acc,
                {slot.value_codes.buf, slot.value_scales.buf, slot.logits.buf,
                 slot.page_out.buf, slot.page_off.buf});
    v.helix_slots.emplace(key, std::move(slot));
  }
}

std::vector<float> VulkanKv::helix_attention(
    size_t layer, size_t kv_head, const std::vector<float>& query_pre_rope,
    size_t query_position, float rope_theta) {
  Impl& v = *impl_;
  auto it = v.helix_slots.find({layer, kv_head});
  if (it == v.helix_slots.end()) {
    throw std::invalid_argument("VulkanKv: no uploaded pages for this head");
  }
  Impl::HelixSlot& s = it->second;
  if (query_pre_rope.size() != s.head_dim) {
    throw std::invalid_argument("VulkanKv: query shape mismatch");
  }
  v.fill_helix_query(s, query_pre_rope, rope_theta);
  v.begin_cmd();
  v.record_helix_logits(s, query_position);
  v.barrier_compute();
  v.record_softmax(s.ds_softmax, s.tokens, s.head_dim);
  v.barrier_compute();
  v.record_helix_acc(s);
  v.submit_and_wait();

  std::vector<float> out;
  Impl::reduce_pages(s.page_out, s.pages, s.head_dim, out);
  return out;
}

std::vector<std::vector<float>> VulkanKv::helix_attention_batch(
    size_t layer, const std::vector<std::vector<float>>& queries,
    size_t query_position, float rope_theta) {
  Impl& v = *impl_;
  std::vector<Impl::HelixSlot*> slots(queries.size());
  for (size_t h = 0; h < queries.size(); ++h) {
    auto it = v.helix_slots.find({layer, h});
    if (it == v.helix_slots.end()) {
      throw std::invalid_argument("VulkanKv: no uploaded pages for head");
    }
    slots[h] = &it->second;
    v.fill_helix_query(*slots[h], queries[h], rope_theta);
  }
  v.begin_cmd();
  for (auto* s : slots) v.record_helix_logits(*s, query_position);
  v.barrier_compute();
  for (auto* s : slots) v.record_softmax(s->ds_softmax, s->tokens, s->head_dim);
  v.barrier_compute();
  for (auto* s : slots) v.record_helix_acc(*s);
  v.submit_and_wait();

  std::vector<std::vector<float>> out(queries.size());
  for (size_t h = 0; h < queries.size(); ++h) {
    Impl::reduce_pages(slots[h]->page_out, slots[h]->pages, slots[h]->head_dim,
                       out[h]);
  }
  return out;
}

void VulkanKv::upload(const RotorQuantCache& cache,
                      const RotorQuantConfig& config) {
  Impl& v = *impl_;
  if (config.block_size != 32 || config.head_dim % 32 != 0) {
    throw std::invalid_argument(
        "VulkanKv: rotor GPU path needs block_size 32 and head_dim % 32 == 0");
  }
  for (auto& [key, slot] : v.rotor_slots) {
    v.destroy_rotor_slot(slot);
  }
  v.rotor_slots.clear();

  std::map<std::pair<size_t, size_t>, std::vector<RotorQuantCache::PageView>>
      grouped;
  for (size_t i = 0; i < cache.page_count(); ++i) {
    RotorQuantCache::PageView view;
    if (cache.page_view(i, &view)) {
      grouped[{view.layer, view.kv_head}].push_back(view);
    }
  }
  const size_t blocks = config.head_dim / config.block_size;
  const size_t code_bytes = config.head_dim / 2;
  for (auto& [key, views] : grouped) {
    Impl::RotorSlot slot;
    slot.head_dim = config.head_dim;
    slot.blocks = blocks;
    slot.pages = views.size();
    for (const auto& view : views) {
      slot.tokens += view.tokens;
    }
    const size_t n = slot.tokens;
    slot.key_codes = v.create_buffer(n * code_bytes);
    slot.key_scales = v.create_buffer(n * blocks * sizeof(float));
    slot.value_codes = v.create_buffer(n * code_bytes);
    slot.value_scales = v.create_buffer(n * blocks * sizeof(float));
    slot.page_off = v.create_buffer((slot.pages + 1) * sizeof(uint32_t));
    slot.rq = v.create_buffer(config.head_dim * sizeof(float));
    slot.logits = v.create_buffer(n * sizeof(float));
    slot.page_out = v.create_buffer(slot.pages * config.head_dim * sizeof(float));

    size_t tok = 0;
    auto* page_off = static_cast<uint32_t*>(slot.page_off.map);
    for (size_t p = 0; p < views.size(); ++p) {
      const auto& view = views[p];
      page_off[p] = static_cast<uint32_t>(tok);
      std::memcpy(static_cast<uint8_t*>(slot.key_codes.map) + tok * code_bytes,
                  view.key_codes, view.tokens * code_bytes);
      std::memcpy(static_cast<float*>(slot.key_scales.map) + tok * blocks,
                  view.key_scales, view.tokens * blocks * sizeof(float));
      std::memcpy(
          static_cast<uint8_t*>(slot.value_codes.map) + tok * code_bytes,
          view.value_codes, view.tokens * code_bytes);
      std::memcpy(static_cast<float*>(slot.value_scales.map) + tok * blocks,
                  view.value_scales, view.tokens * blocks * sizeof(float));
      tok += view.tokens;
    }
    page_off[slot.pages] = static_cast<uint32_t>(tok);

    slot.ds_logits = v.alloc_set(v.rotor_logits.dsl);
    v.write_set(slot.ds_logits, {slot.key_codes.buf, slot.key_scales.buf,
                                 slot.rq.buf, slot.logits.buf});
    slot.ds_softmax = v.alloc_set(v.softmax.dsl);
    v.write_set(slot.ds_softmax, {slot.logits.buf});
    slot.ds_acc = v.alloc_set(v.rotor_acc.dsl);
    v.write_set(slot.ds_acc,
                {slot.value_codes.buf, slot.value_scales.buf, slot.logits.buf,
                 slot.page_out.buf, slot.page_off.buf});
    v.rotor_slots.emplace(key, std::move(slot));
  }
}

std::vector<float> VulkanKv::rotor_attention(const RotorQuantCache& cache,
                                             size_t layer, size_t kv_head,
                                             const std::vector<float>& query) {
  Impl& v = *impl_;
  auto it = v.rotor_slots.find({layer, kv_head});
  if (it == v.rotor_slots.end()) {
    throw std::invalid_argument("VulkanKv: no uploaded pages for this head");
  }
  Impl::RotorSlot& s = it->second;
  const std::vector<float> rq = cache.rotate(query);
  std::memcpy(s.rq.map, rq.data(), rq.size() * sizeof(float));

  v.begin_cmd();
  v.record_rotor_logits(s);
  v.barrier_compute();
  v.record_softmax(s.ds_softmax, s.tokens, s.head_dim);
  v.barrier_compute();
  v.record_rotor_acc(s);
  v.submit_and_wait();

  std::vector<float> acc;
  Impl::reduce_pages(s.page_out, s.pages, s.head_dim, acc);
  return cache.unrotate(acc);
}

std::vector<std::vector<float>> VulkanKv::rotor_attention_batch(
    const RotorQuantCache& cache, size_t layer,
    const std::vector<std::vector<float>>& queries) {
  Impl& v = *impl_;
  std::vector<Impl::RotorSlot*> slots(queries.size());
  for (size_t h = 0; h < queries.size(); ++h) {
    auto it = v.rotor_slots.find({layer, h});
    if (it == v.rotor_slots.end()) {
      throw std::invalid_argument("VulkanKv: no uploaded pages for head");
    }
    slots[h] = &it->second;
    const std::vector<float> rq = cache.rotate(queries[h]);
    std::memcpy(slots[h]->rq.map, rq.data(), rq.size() * sizeof(float));
  }
  v.begin_cmd();
  for (auto* s : slots) v.record_rotor_logits(*s);
  v.barrier_compute();
  for (auto* s : slots) v.record_softmax(s->ds_softmax, s->tokens, s->head_dim);
  v.barrier_compute();
  for (auto* s : slots) v.record_rotor_acc(*s);
  v.submit_and_wait();

  std::vector<std::vector<float>> out(queries.size());
  for (size_t h = 0; h < queries.size(); ++h) {
    Impl::reduce_pages(slots[h]->page_out, slots[h]->pages, slots[h]->head_dim,
                       out[h]);
    out[h] = cache.unrotate(out[h]);
  }
  return out;
}

}
