[package]
name = "llamas-cli"
edition.workspace = true
license.workspace = true
version.workspace = true

[[bin]]
name = "llamas-cli"
path = "src/main.rs"

[dependencies]
clap.workspace = true
llamas-core = { path = "../llamas-core" }
futures-core = "0.3"
rand = "0.8"
tracing.workspace = true

[dev-dependencies]
assert_cmd = "2"
